# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Animated Splash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios'

  # Pods for Animated Splash

end
